name: Discord Commit Notification

on:
  push:
    branches:
      - master

jobs:
  notify-discord:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: filispeen/discord-notifier@v1
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
